server:
  port: ${SERVER_PORT:8081}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: workflow-center
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./workflow-center-app/data/workflow-center;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never
flowable:
  database-schema-update: true
  check-process-definitions: true
  async-executor-activate: false
  database-type: h2
management:
  endpoints:
    web:
      exposure:
        include: health,info
workflow-center:
  security:
    internal-token: ${WORKFLOW_CENTER_SECURITY_INTERNAL_TOKEN:change-me-in-prod}
logging:
  level:
    root: INFO
    com.company.workflow: INFO
